mlearn/mlapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from mlapp import views

app_name = 'mlapp'

urlpatterns = [
    url(r'^upload/',views.upload.as_view(), name = 'upload'),
    url(r'^$',views.index.as_view(), name = 'index'),
    url(r'^preprocessing/',views.preprocessing.as_view(), name = 'preprocessing'),
    url(r'^modelling/',views.modelling.as_view(), name = 'modelling'),
]

mlearn/mlearn/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mlapp import views

urlpatterns = [
    url(r'^admin', admin.site.urls),
    url(r'^', include('mlapp.urls'))
]

mlearn/mlapp/models.py
from django.db import models
from static.py.funcs import OverwriteStorage
import json

# Create your models here.
class DownloadedFile(models.Model):
    docfile = models.FileField(storage=OverwriteStorage(), upload_to='downloaded/')

class CurrentFile(models.Model):
    filename = models.CharField(max_length=300)

class Prepross(models.Model):
    filename = models.CharField(max_length=300)
    coltype = models.CharField(max_length=300)
    assvar = models.CharField(max_length=300)
    missingvalues = models.CharField(max_length=300)
    trainingset_size = models.IntegerField()
    featscaling = models.CharField(max_length=300)

mlearn/mlapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from mlapp.models import DownloadedFile, CurrentFile,Prepross
from static.py.funcs import StrToList
import pandas as pd
import os
import plotly.offline as opy
import plotly.graph_objs as go
from sklearn import metrics
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier

class index(TemplateView):
    template_name = 'index.html'

    def post(self, request, **kwargs):
        if request.method == 'POST':
            current_file = CurrentFile(filename = list(request.POST.keys())[1])
            current_file.save()
            context = {}
            context['fileselected'] = list(request.POST.keys())[1]
            context['test'] = 'a'
            return render(request,'index.html', context)

    def __str__(self):
        return self.name

class upload(TemplateView):
    template_name = 'upload.html'

    def post(self, request, **kwargs):
        if request.method == 'POST' and request.FILES["docfile"]:

            downloaded_file = DownloadedFile(docfile=request.FILES['docfile'])
            downloaded_file.save()
            downloaded_file.delete() # it deletes only from database
            return render(request,'upload.html')

    def __str__(self):
        return self.name

class preprocessing(TemplateView):
    template_name = 'preprocessing.html'
    #model = Prepross
    #fields = ('file_name','coltype','Xvars','Yvar','onehot','featscaling','na_omit')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        context = {}
        try:
            file_name = CurrentFile.objects.order_by('-id')[0].filename
            df = pd.read_csv(os.path.join('media\downloaded', file_name))
            count_nan = len(df) - df.count()
            row_count = df.count()[0]
            file_type = pd.concat([df.dtypes, count_nan, df.nunique()], axis=1)
            file_type.columns = ("Type", "NA count", "Count distinct")

            context['file_type'] = file_type
            context['row_count'] = row_count
        except:
            file_name = 'Please select one file'


        context['file_name'] = file_name
        return context

    def post(self, request, **kwargs):
        if request.method == 'POST':

            # Entry to model
            prep_file = Prepross.objects.get_or_create(filename = CurrentFile.objects.order_by('-id')[0].filename,
                                  coltype = request.POST.getlist('coltype'),
                                    assvar = request.POST.getlist('assvar'),
                            missingvalues = request.POST.getlist('missingvalues'),
                         trainingset_size = request.POST['trainingset_size'],
                              featscaling = request.POST.getlist('featscaling')
                                   )

            # Get dataframe and change data type
            context = {}
            file_name = CurrentFile.objects.order_by('-id')[0].filename
            coltype = request.POST.getlist('coltype')
            coltype = dict([i.split(':', 1) for i in coltype])
            df = pd.read_csv(os.path.join('media\downloaded', file_name), dtype= coltype)
            row_count = df.count()[0]

            # Keep only selected columns
            assvar = request.POST.getlist('assvar')
            xcols0 = [s for s in assvar if ":X" in s]
            xcols = [i.split(':', 1)[0] for i in xcols0]
            ycol0 = [s for s in assvar if ":y" in s]
            ycol = [i.split(':', 1)[0] for i in ycol0]
            cols = xcols + ycol
            df = df[cols]

            xcols = ', '.join(xcols)
            ycol = ', '.join(ycol)
            missing = request.POST.getlist('missingvalues')
            missing = ', '.join(missing)
            trainingset_s = request.POST.getlist('trainingset_size')
            trainingset_s = ', '.join(trainingset_s)
            testset_s = 100 - int(trainingset_s)
            feat =  request.POST['featscaling']

            # Taking care of missing data
            if missing == "no":
                if len(df) != len(df.dropna()):
                    context['selecty'] = 'Your data seem to have Missing Values'
                else:
                    df = df.dropna()

            # Return error if columns are not selected
            if len(ycol0) != 1:
                context['selecty'] = 'Please select one y variable'

            elif len(xcols0) < 1:
                context['selecty'] = 'Please select one or more X variables'

            else:
            # Plot
                graph = {}
                for i in df.columns:
                    layout = go.Layout(autosize=False, width=400, height=400,
                        title= i,
                        xaxis=dict(title='Value'),
                        yaxis=dict(title='Count'),
                        bargap=0.2,
                        bargroupgap=0.1)
                    data = go.Figure(data=[go.Histogram(x=df[i])], layout=layout)
                    graph[i] = opy.plot(data, include_plotlyjs=False, output_type='div')
                context['graph'] = graph

            context['xcols'] = xcols
            context['ycol'] = ycol
            context['missing'] = missing
            context['trainingset_s'] = trainingset_s
            context['testset_s'] = testset_s
            context['feat'] = feat
            context['file_name'] = file_name
            context['row_count'] = row_count
            return render(request,'preprocessing.html', context)

    def __str__(self):
        return self.name


class modelling(TemplateView):
    template_name = 'modelling.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        context = {}
        try:
            # filter avoids csv file (CurrentFile ansd Prepross model) to be different from preprocessing parameters
            prepross_dict = Prepross.objects.filter(filename = CurrentFile.objects.order_by('-id')[0].filename).order_by('-id').values()[0]
            file_name = prepross_dict['filename']
            assvar = StrToList.strtolist(prepross_dict['assvar'])
            xcols = [s for s in assvar if ":X" in s]
            xcols = [i.split(':', 1)[0] for i in xcols]
            ycol = [s for s in assvar if ":y" in s]
            ycol = [i.split(':', 1)[0] for i in ycol]

            xcols = ', '.join(xcols)
            ycol = ', '.join(ycol)
            missing = StrToList.strtolist(prepross_dict['missingvalues'])
            missing = ', '.join(missing)
            trainingset_s = prepross_dict['trainingset_size']
            testset_s = 100 - prepross_dict['trainingset_size']
            feat =  StrToList.strtolist(prepross_dict['featscaling'])
            feat= ', '.join(feat)
            context['xcols'] = xcols
            context['ycol'] = ycol
            context['missing'] = missing
            context['trainingset_s'] = trainingset_s
            context['testset_s'] = testset_s
            context['feat'] = feat
            context['file_name'] = file_name

        except:
            prepross_dict = 'Please submit preprocessing'

        context['prepross_dict'] = prepross_dict

        return context

    def post(self, request, **kwargs):
        if request.method == 'POST':

            context = {}
            # filter avoids csv file (CurrentFile ansd Prepross model) to be different from preprocessing parameters
            prepross_dict = Prepross.objects.filter(filename = CurrentFile.objects.order_by('-id')[0].filename).order_by('-id').values()[0]
            file_name = prepross_dict['filename']

            # Get dataframe and change data type
            coltype = StrToList.strtolist(prepross_dict['coltype'])
            coltype = dict([i.split(':', 1) for i in coltype])
            df = pd.read_csv(os.path.join('media\downloaded', file_name), dtype= coltype)

            assvar = StrToList.strtolist(prepross_dict['assvar'])
            xcols = [s for s in assvar if ":X" in s]
            xcols = [i.split(':', 1)[0] for i in xcols]
            ycol = [s for s in assvar if ":y" in s]
            ycol = [i.split(':', 1)[0] for i in ycol]
            cols = xcols + ycol
            df = df[cols]

            # Taking care of missing data
            if prepross_dict['missingvalues'] == "['na_omit']":
                df = df.dropna()


            X = df[xcols]
            X = pd.get_dummies(X, drop_first=True)
            X = X.values
            y = df[ycol]
            y = pd.get_dummies(y, drop_first=True)
            y = y.values

            # Splitting the dataset into the Training set and Test set
            testset_size = 1 - (prepross_dict['trainingset_size']/100)
            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = testset_size)

            # Feature Scaling
            if prepross_dict['featscaling'] != "['no']":
                sc = StandardScaler()
                X_train = sc.fit_transform(X_train)
                X_test = sc.transform(X_test)

            p2 = {} # dictionary for plot
            accuracy = {} # dictionary for cm
            # Fit Classifications
            for k in request.POST.getlist('mlmodel'):
                if 'RF' == k:
                # Fitting Random Forest Classification to the Training set
                    classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')
                elif 'logreg' == k:
                    # Fitting LogisticRegression to the Training set

mlearn/mlapp/templates/mlapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Machine learning</title>
    <!-- Latest compiled and minified CSS -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static "css/style.css" %}"/>

  <script src="https://cdn.plot.ly/plotly-latest.min.js" ></script>

  </head>
  <body>
    <div class="container">
    <nav class="navbar navbar-dark bg-dark">
          <a class="navbar-brand " href="{% url 'mlapp:index' %}">
            <div class="input-group" >
            <svg class="u-header-logo" >
                              <path class="g-fill-primary" d="M 24.69,2.31 C 28.08,5.71 28.08,21.29 24.69,24.69 22.04,27.33 18.43,26.99 15.00,27.00 11.50,27.01 6.00,27.54 3.15,25.40 1.91,24.48 1.15,23.41 0.60,21.98 -0.29,19.67 -0.29,7.33 0.60,5.02 1.51,2.64 2.23,2.45 4.06,1.02 8.46,-0.49 21.22,-1.15 24.69,2.31 Z">
                              </path>
                              <path class="g-fill-white" d="M 33.00,2.00 C 33.00,2.00 33.00,21.00 33.00,21.00 33.00,21.00 30.00,21.00 30.00,21.00 30.00,21.00 30.00,2.00 30.00,2.00 30.00,2.00 33.00,2.00 33.00,2.00 Z
                                                            M 10.00,10.00 C 13.43,7.53 14.39,8.13 18.00,10.00 26.70,3.74 26.00,16.10 26.00,21.00 26.00,21.00 23.00,21.00 23.00,21.00 23.00,21.00 23.00,11.00 23.00,11.00 17.25,12.84 18.02,15.65 18.00,21.00 18.00,21.00 15.00,21.00 15.00,21.00 15.00,21.00 15.00,11.00 15.00,11.00 9.25,12.84 10.02,15.65 10.00,21.00 10.00,21.00 7.00,21.00 7.00,21.00 7.00,21.00 7.00,8.00 7.00,8.00 7.00,8.00 10.00,10.00 10.00,10.00 Z
                                                            M 36.66,13.02 C 37.81,7.52 45.84,4.97 48.00,15.00 48.00,15.00 39.00,15.00 39.00,15.00 41.97,18.44 42.51,18.73 47.00,18.00 42.91,24.11 35.29,19.60 36.66,13.02 Z M 60.40,11.07 C 61.23,13.04 61.00,18.69 61.00,21.00 58.83,20.90 54.00,21.10 52.33,19.97 51.60,19.47 51.05,18.81 50.91,17.91 50.32,14.13 55.63,14.08 58.00,14.00 55.85,10.30 55.11,10.59 51.00,11.07 53.52,7.24 58.60,7.01 60.40,11.07 Z
                                                            M 68.00,10.00 C 68.00,10.00 72.00,8.00 72.00,8.00 69.50,15.01 68.04,10.10 68.00,21.00 68.00,21.00 65.00,21.00 65.00,21.00 65.00,21.00 65.00,8.00 65.00,8.00 65.00,8.00 68.00,10.00 68.00,10.00 Z
                                                            M 82.86,8.70 C 87.02,10.15 86.00,17.42 86.00,21.00 86.00,21.00 83.00,21.00 83.00,21.00 83.00,21.00 82.00,10.00 82.00,10.00 77.51,13.83 78.02,15.44 78.00,21.00 78.00,21.00 75.00,21.00 75.00,21.00 75.00,21.00 75.00,8.00 75.00,8.00 80.02,9.61 80.28,7.80 82.86,8.70 Z
                                                            M 39.00,13.00 C 39.00,13.00 45.00,13.00 45.00,13.00 42.78,9.72 41.22,9.72 39.00,13.00 Z M 53.00,16.00 C 53.00,16.00 53.00,18.00 53.00,18.00 56.54,18.47 56.80,18.39 58.00,15.00 58.00,15.00 53.00,16.00 53.00,16.00 Z">
                              </path>
            </svg>
          </a>
          <a class="nav-link" href="{% url 'mlapp:upload' %}"> Upload <span class="sr-only">(current)</span></a>
          <a class="nav-link" href="{% url 'mlapp:index' %}"> Start New Project <span class="sr-only">(current)</span></a>
          <a class="nav-link" href="{% url 'mlapp:preprocessing' %}"> Preprocessing <span class="sr-only">(current)</span></a>
          <a class="nav-link" href="{% url 'mlapp:modelling' %}"> Machine Learning <span class="sr-only">(current)</span></a>
          <a class="nav-link" href="{% url 'admin:index' %}"> Admin <span class="sr-only">(current)</span></a>
          </div>

    </nav>
    </div>

    <div class="container">

    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>


  </body>
</html>

mlearn/mlapp/templates/mlapp/index.html
<!DOCTYPE html>
{% extends "base.html" %}
    {% block body_block%}


<h2>Select a file</h2>

<form method="POST" action="." enctype="multipart/form-data" class="form-horizontal form-inline">
{% csrf_token %}

{% for i in listfiles %}
  <div>
    <button type="submit" name={{i}} class="fileUpload btn btn-primary">{{i}}</button>
  </div>
{% endfor %}
</form>

{% if fileselected %}

<p></p>
<h2>Current project</h2>
<p class="fileUpload">{{fileselected}}</p>

{% endif %}

{% endblock %}

mlearn/mlapp/templates/mlapp/modelling.html
<!DOCTYPE html>
{% extends "base.html" %}
    {% block body_block%}

<h2>Machine Learning</h2>
<p class="fileUpload">{{file_name}}</p>

<div class="jumbotron">

  <form class="" action="index.html" method="post">
    {% csrf_token %}
    <div class="row">
      <div class="fileUpload col-lg-4 col-xs-6">
        <label>  <b>Select Machine learning algorithm: <br>
                    Classification </b></label>
        <select multiple class="form-control" name="mlmodel">
                <option selected disabled hidden> - Select one - </option>
                <option value='logreg'>Logistic Regression</option>
                <option value='RF'>Random Forest</option>
                <option value='xgboost'>xgboost</option>
             </select>
      </div>

        <div class="fileUpload col-lg-6 col-xs-6">
          <p> <b>Your data selections: </b> <br>
              <b>X variables:</b> {{xcols}} <br>
              <b>Y variables:</b> {{ycol}} <br>
              <b>Missing values:</b> {{missing}} <br>
              <b>Training set size:</b> {{trainingset_s}}% <br>
              <b>Test set size:</b> {{testset_s}}%<br>
              <b>Feature scaling:</b> {{feat}} <br></p>
        </div>
    </div>
      <div class="fileUpload btn btn-primary">
        <span>Submit</span>
          <div>
              <input type="Submit" name="prepross_submit" class="upload">
          </div>
      </div>
  </form>
</div>


<div class="row">
  {% for key, acc, true_negative, false_positive, false_negative, true_positive in accuracy.values %}
  <div class="table-responsive col-lg-4 col-xs-6">
    <h5>{{key}} accuracy = {{acc}}</h5>
      <table class = 'table'>
        <tr>
          <th>  </th>
          <th> Predicted NO </th>
          <th> Predicted YES </th>
        </tr>
        <tr>
          <td> <b>Actual NO</b> </td>
          <td> {{true_negative}} </td>
          <td> {{false_positive}} </td>
        </tr>
        <tr>
          <td> <b>Actual YES</b> </td>
          <td> {{false_negative}} </td>
          <td> {{true_positive}} </td>
        </tr>

      </table>
  </div>
 {% endfor %}
</div>

        <div class = 'container col-md-8'>
            {{ graph|safe }}
        </div>


{% endblock %}

mlearn/mlapp/templates/mlapp/upload.html
<!DOCTYPE html>
{% extends "base.html" %}
    {% block body_block%}

<h2>Upload new file</h2>


<div class="form-horizontal form-inline">

  <form method="POST" enctype="multipart/form-data" >
  {% csrf_token %}
    <div class="fileUpload btn btn-primary">
      <span>Upload new file</span>
      <div>
          <input type="file" name="docfile" required="True" class="upload" onchange="javascript:this.form.submit();">
      </div>
    </div>

  </form>


</div>

{% endblock %}